apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- ../route

patches:
  - patch: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: example
      spec:
        subdomain: example
