apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: traefik/whoami:latest
          name: whoami
          environment:
              WHOAMI_PORT_NUMBER: 8080
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
