apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: example
        annotations:
          metallb.universe.tf/address-pool: public
      spec:
        type: LoadBalancer
